# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package (Nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  prepare:
    runs-on: self-hosted
    permissions:
      contents: read
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Debug
      run: git log --pretty=fuller --name-only -20
      
    - name: Check for commits in last 26h
      id: changes
      if: github.event_name == 'schedule'
      run: |
        LOG_OUTPUT=$(git log \
          --since='26 hours ago' \
          --oneline \
          -- . ':(exclude).github/**' \
          | grep -v '\[bot\]' \
          | grep -v 'github-actions' \
          | grep -v '^\[NIGHTLY\]')

        echo "Git log output:"
        echo "$LOG_OUTPUT"
        
        if echo "$LOG_OUTPUT" | grep -q .; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Detect SNAPSHOT version
      id: snapshot
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION"
        
        if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
          echo "is_snapshot=true" >> $GITHUB_OUTPUT
        else
          echo "is_snapshot=false" >> $GITHUB_OUTPUT
        fi

    - name: Decide if pipeline should run
      id: decision
      run: |
        if [[ "${{ steps.snapshot.outputs.is_snapshot }}" == "true" && "${{ steps.changes.outputs.has_changes }}" == "true" ]]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi

  format:
    runs-on: self-hosted
    needs: prepare
    if: needs.prepare.outputs.should_run == 'true'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Apply formatting
        run: mvn -B spotless:apply

      - name: Commit & push if needed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git diff --cached --quiet || git commit -m "[NIGHTLY] Apply code formatting"

          git push || echo "Push failed, continuing..."

  build:
    runs-on: self-hosted
    needs: format
    if: needs.prepare.outputs.should_run == 'true'

    permissions:
      contents: write

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
    - uses: actions/setup-java@v5
      if: >
        steps.snapshot.outputs.is_snapshot == 'true' &&
        (
          github.event_name != 'schedule' ||
          steps.changes.outputs.has_changes == 'true'
        )
      with:
        distribution: temurin
        java-version: 17
        server-id: nexus.kbra.lu-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
            
    - name: Build with Maven
      if: >
        steps.snapshot.outputs.is_snapshot == 'true' &&
        (
          github.event_name != 'schedule' ||
          steps.changes.outputs.has_changes == 'true'
        )
      run: mvn -B clean compile package install deploy
